import Head from 'next/head';

import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { Hero } from '@/components/hero';
import { About } from '@/components/about';
import { Work } from '@/components/work';
import { Dishes } from '@/components/dishes';
import { Chefs } from '@/components/chefs';
import { Recipes } from '@/components/recipes';
import { Social } from '@/components/social';

export default function Home() {
  return (
    <>
      <Head>
        <title>Healthy Food</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/logo.svg' />
      </Head>
      <Header />
      <main>
        <Hero />
        <About />
        <Work />
        <Dishes />
        <Chefs />
        <Recipes />
        <Social />
      </main>
      <Footer />
    </>
  );
}
