import Head from 'next/head';

import Header from '@/components/header/header';
import Hero from '@/components/hero/hero';

export default function Home() {
  return (
    <>
      <Head>
        <title>Healthy Food</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/logo.svg' />
      </Head>
      <Header />
      <main>
        <Hero />
      </main>
    </>
  );
}
